#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-init-staytus ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-web ]; then
	sleep 2	
	echo 'Initialization Complete' >/tmp/state/20-worker
fi 

cd /app/staytus
echo ''
echo '** [staytus] Starting Puma'
exec bundle exec puma -C config/puma.rb
