#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="staytus"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting Puma"
cd /app/staytus
exec bundle exec puma -C config/puma.rb
