#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="staytus-worker"

while [ ! -f /tmp/state/10-staytus ]
do
  sleep 1
done

liftoff

print_info "Starting  Worker"

cd /app/staytus
exec bundle exec rake jobs:work;
