version: '2'

services:
  staytus-app:
    image: tiredofit/staytus:latest
    container_name: staytus-app
    links:
      - staytus-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #Custom Theme Support
      - ./custom:/assets/staytus
    environment:
      - VIRTUAL_HOST=status
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=status
      - LETSENCRYPT_EMAIL=email@example.org

      - ZABBIX_HOSTNAME=staytus-app

      - DB_HOST=staytus-db
      - DB_NAME=staytus
      - DB_USER=staytus
      - DB_PASS=password

      - STAYTUS_SMTP_HOSTNAME=postfix-relay
      - STAYTUS_SMTP_PORT=25
      #- STAYTUS_SMTP_USERNAME=user
      #- STAYTUS_SMTP_PASSWORD=password


    networks:
      - proxy-tier
    restart: always

  staytus-db:
    container_name: status-db
    image: tiredofit/mariadb
    volumes:
      - /var/local/db/staytus:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=staytus
      - MYSQL_USER=staytus
      - MYSQL_PASSWORD=password
      - ZABBIX_HOSTNAME=staytus-db
    networks:
      - proxy-tier
    restart: always

  staytus-db-backup:
    container_name: staytus-db-backup
    image: tiredofit/mariadb-backup
    links:
      - staytus-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - DB_SERVER=staytus-db
      - DB_NAME=staytus
      - DB_USER=staytus
      - DB_PASSWORD=password
      - DB_DUMP_FREQ=1440
      #- DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy


