#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-node ]; then
sleep 2

	### Make sure that DB is accessible
	while true; do
	  mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
	  out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
	  echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
	  if [ $? -eq 0 ]; then
	    echo "** [staytus] Server is up !"
	    break
	  fi
	  echo "** [staytus] Server "$DB_HOST" is not available. Retying in 2 seconds"
	  sleep 2
	done


	## Perform Configuration Edits
	  cp /assets/config/database.yml /app/staytus/config/database.yml
	  sed -i -e "s/<DB_HOST>/$DB_HOST/g" /app/staytus/config/database.yml
	  sed -i -e "s/<DB_PORT>/$DB_PORT/g" /app/staytus/config/database.yml
	  sed -i -e "s/<DB_NAME>/$DB_NAME/g" /app/staytus/config/database.yml
	  sed -i -e "s/<DB_USER>/$DB_USER/g" /app/staytus/config/database.yml
	  sed -i -e "s/<DB_PASS>/$DB_PASS/g" /app/staytus/config/database.yml

	### Theme Support
	if [ -d /assets/staytus ] ; then
	   echo "** [staytus] Custom Files Found, Copying over top of Master.."
	   cp -R /assets/staytus/* /app/staytus/
	fi

	cd /app/staytus
	
	## Fix Production.rb Log Issue
	if [ "$RAILS_ENV" = "production" ];  then 
        sed -i -e "s/config.log_level = :debug/config.log_level = :warn/g" /app/staytus/config/environments/production.rb
		if [ "DEBUG_MODE" = "true" ] || [ "DEBUG_MODE" = "TRUE" ];  then
		  sed -i -e "s/config.log_level = :warn/config.log_level = :debug/g" /app/staytus/config/environments/production.rb
		fi
    fi

	bundle exec rake staytus:build staytus:install

    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-node
fi

cd /app/staytus
echo ''
echo '** [staytus] Starting Foreman'
exec foreman start

